name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    permissions:
      packages: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: |
        msbuild -t:restore -property:Configuration=${{ matrix.configuration }}
        msbuild -t:build -property:Configuration=${{ matrix.configuration }}

    - name: Upload license
      uses: actions/upload-artifact@v3
      with:
        name: MEME
        path: LICENSE
        if-no-files-found: error
    - name: Upload application
      uses: actions/upload-artifact@v3
      with:
        name: MEME
        path: src/GUI/bin/${{ matrix.configuration }}/net6.0/**
        if-no-files-found: error
